service: sagemakerscheduler

provider:
  name: aws
  runtime: python2.7
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - sagemaker:DescribeTrainingJob
        - sagemaker:CreateTrainingJob
      Resource: "arn:aws:sagemaker:*:*:*"

stage: dev
region: us-east-1

functions:
  main:
    handler: handler.main
    events:
      - schedule: rate(15 minutes)
    environment:
      training_job_name: "DEMO-imageclassification-2018-05-10-09-58-12"
      training_name_prefix: "imageclassification"
      instance_type: "p3.2xlarge"
      instance_count: "2"
